### ISSUE TITLE
File Name Inclusion

### ISSUE THREAD

**Issue by RichardSummers** [IntelligentVisibility/filmStripImageBrowser#1]
The addition of displaying the file name of each file either above or below the image would be advantageous.

**Comment by IntelligentVisibility** [comment]
Would you want the image name + filetyle (.png for example) or just the image name?

**Comment by RichardSummers** [comment]
I presume it would need the full name (including any spaces) and extension , in order for the "double click to open in default app" addition to function correctly?

If not, then I don't suppose it matters much?

**Comment by devtimi** [comment]
I elected for the easiest route: storing the `FolderItem` in the `PictureClass`.

This provides for so much more flexibility. You can get the file name, with or without extension; and it makes #2 so much easier because you can just `.Launch` the stored `FolderItem`.

**Comment by IntelligentVisibility** [comment]
Perfect thank you Tim!

**Comment by IntelligentVisibility** [comment]
Richard/Tim - Adding names is aesthetically not looking good - only when the filename is large. Due to this I added an option to allow custom image spacing. My only last thought is to wrap the long filenames at the width boundary of it's image owner. Thoughts guys?

**Comment by RichardSummers** [comment]
How about - display the filename in a label, upon mouseover?
This way the filename would only be shown for the moused over image of interest.

**Comment by IntelligentVisibility** [comment]
Mouseover labeling is always a mess. How is this?
<img width="808" alt="screen shot 2016-12-17 at 9 37 00 am" src="https://cloud.githubusercontent.com/assets/5958555/21287575/7df7999e-c43c-11e6-974a-5c81545c19b8.png">

**Comment by RichardSummers** [comment]
That looks better :)

**Comment by IntelligentVisibility** [comment]
<img width="776" alt="screen shot 2016-12-17 at 9 39 59 am" src="https://cloud.githubusercontent.com/assets/5958555/21287588/d9869ce2-c43c-11e6-9786-dddfdee85be9.png">

**Comment by IntelligentVisibility** [comment]
Awesome Ill commit and close this issue ;)

**Comment by IntelligentVisibility** [comment]
Completed and verified

**Comment by IntelligentVisibility** [comment]
I have another idea - a Boolean to show/hide name.

**Comment by RichardSummers** [comment]
Just noticed, when the user has large images (not just relatively small icon images), the percentage has to be reduced in order to fit in the filmstrip - which is fine - however - the filenames then also reduced to a miniscule size and are totally unreadable :(
