### ISSUE TITLE
PictureClass has no member named imageRect

### ISSUE THREAD

**Issue by devtimi** [IntelligentVisibility/filmStripImageBrowser#10]
Either I updated wrong, or it's missing parts.
Can't build, getting the error that's the title.

What did you do? What should this be?

**Comment by IntelligentVisibility** [comment]
You may have pulled the wrong branch? re-pull the master?

realbasic.Rect creates an invisible rectangle that tracks the left/top of each image. This gives us a bunch of nice interactive functions to use. I use this all of the time with my canvas based apps that require alot of mouse interaction. Overkill for this use, but you never know what else this will turn into :)

**Comment by devtimi** [comment]
No, it's not found on the Master.
https://raw.githubusercontent.com/IntelligentVisibility/filmStripImageBrowser/master/PictureClass.xojo_code
Search for imageRect

**Comment by IntelligentVisibility** [comment]
Let me see what I did wrong :)
-=-=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-
Michael Cotrone
CEO / President
Intelligent Visibility, Inc.

PO BOX 348
3912 Old Berkshire Road, Suite 200
Browns Summit, NC 27214

() +1.336.908.8580
()@IntelligentViz
() mikec@intelligentvisibility.com <mailto:mikec@intelligentvisibility.com>

**Comment by IntelligentVisibility** [comment]
I merged something wrong as my changes aren’t in master yet. Sorry .. Checking why now.Love/hate git.

**Comment by IntelligentVisibility** [comment]
I screwed up by waxing that property some how in between testing and committing :)
