### ISSUE TITLE
Miniscule Filenames.

### ISSUE THREAD

**Issue by RichardSummers** [IntelligentVisibility/filmStripImageBrowser#11]
Filenames become absolutely miniscule when large images are displayed at low percentages (in order to see the entire image).

Try loading a 6000 x 4000 image, and viewing at 10%   :)

**Comment by IntelligentVisibility** [comment]
You can't read 1pt? 🎱

**Comment by RichardSummers** [comment]
Not without the hubble telescope - no :)

**Comment by IntelligentVisibility** [comment]
Removed scaling all together on the Names.
