### ISSUE TITLE
Mouseover Function

### ISSUE THREAD

**Issue by RichardSummers** [IntelligentVisibility/filmStripImageBrowser#5]
The ability to pause a scrolling filmstrip upon mouse over, and then continue with the animation upon mouse out.

**Comment by devtimi** [comment]
FYI, this can be accomplished already. CanvasClass already inherits MouseEnter and MouseExit from Canvas. Just stop the Timer and start the Timer in these events.

I will keep this request in mind if I end up being the one to internalize the animation timer.

**Comment by IntelligentVisibility** [comment]
Complete and tested
