### ISSUE TITLE
Thumbnail size should be maximum bounds

### ISSUE THREAD

**Issue by devtimi** [IntelligentVisibility/filmStripImageBrowser#6]
The thumbnail size should be maximum bounds for proportional scaling rather than a "stretch and resize to this box" operation.

**Comment by IntelligentVisibility** [comment]
This has been completed with Issue #4 - where I removed scaling the image based on thumbnailW and thumbnailH in pixels. I know am scaling the image based on the Percentage chosen for scale factor (double).
