### ISSUE TITLE
Percentages Issue

### ISSUE THREAD

**Issue by RichardSummers** [IntelligentVisibility/filmStripImageBrowser#8]
Percentages cause images to sometimes overlap.

**Comment by IntelligentVisibility** [comment]
<img width="808" alt="screen shot 2016-12-17 at 9 37 00 am" src="https://cloud.githubusercontent.com/assets/5958555/21287665/09c1e23e-c43f-11e6-96ac-a7aa822ca3f3.png">
<img width="776" alt="screen shot 2016-12-17 at 9 39 59 am" src="https://cloud.githubusercontent.com/assets/5958555/21287666/09c28432-c43f-11e6-9ceb-2a3b8ee76654.png">
