### ISSUE TITLE
Filename Issue

### ISSUE THREAD

**Issue by RichardSummers** [IntelligentVisibility/filmStripImageBrowser#9]
Only the first filename appears under the first image. All other images have no filenames?

**Comment by IntelligentVisibility** [comment]
You were pulling the wrong branch most likely. Please re-pull it now and verify?

**Comment by IntelligentVisibility** [comment]
![screen shot 2016-12-17 at 9 51 52 am](https://cloud.githubusercontent.com/assets/5958555/21287646/73250f4a-c43e-11e6-828d-247270c97775.png)

**Comment by IntelligentVisibility** [comment]
<img width="808" alt="screen shot 2016-12-17 at 9 37 00 am" src="https://cloud.githubusercontent.com/assets/5958555/21287658/ed065558-c43e-11e6-8055-e7ef753534d9.png">
<img width="776" alt="screen shot 2016-12-17 at 9 39 59 am" src="https://cloud.githubusercontent.com/assets/5958555/21287659/ed086afa-c43e-11e6-9ba2-496a7b2202f2.png">

**Comment by RichardSummers** [comment]
Hmm, I don't have gitflow, but I must have the latest version, as it has the percentages functionality added?

I will try downloading again though.

Have you tried it with say a folder of 20 images?
Thanks.
